# Generated by Django 3.0.5 on 2020-06-10 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='continent',
            new_name='city',
        ),
    ]
